### ISSUE TITLE
Prefix for global announcements

### ISSUE THREAD

**Issue by Rmarmorstein** [dextonanderson/BroadcastIt#1]
On the spigot page, I did not see a prefix option for the global announcements. It would be nice to see a global announcement option to have a prefix.

Thanks!

**Comment by dextonanderson** [comment]
For now, use the prefix for each of the global messages. I will work out a way to add this though.

**Comment by Rmarmorstein** [comment]
Awesome, That's what I've been doing. Thank you!

**Comment by dextonanderson** [comment]
Added.
